namespace SerialAPI.BidCoSFrames;

public enum AnswerStatus
{
	ACK = 0,
	ACK_STATUS = 1,
	ACK_IGNORED = 2,
	ACK_CORRECTED = 3,
	ACK_AES = 4,
	NAK = 128,
	NAK_BUSY = 129,
	NAK_OUT_OF_MEMORY_NOT_PROCESSED = 130,
	NAK_OUT_OF_MEMORY_PARTIAL_PROCESSED = 131,
	NAK_INVALID_TARGET = 132,
	NAK_INVALID_CHANNEL = 133
}
