namespace SerialAPI;

public enum AddressExtensionType : byte
{
	SINGLE_HOP,
	FIRST_ROUTED,
	IN_PATH,
	LAST_ROUTED,
	FIRST_ROUTED_IP6,
	IN_PATH_TO_IP6,
	IN_PATH_FROM_IP6,
	LAST_ROUTED_IP6,
	FIRST_ROUTED_IP4,
	IN_PATH_TO_IP4,
	IN_PATH_FROM_IP4,
	LAST_ROUTED_IP4
}
