namespace SerialAPI;

public enum ICMP_type : byte
{
	DESTINATION_UNREACHABLE = 1,
	PACKET_TOO_BIG = 2,
	TIME_EXCEEDED = 3,
	PARAMETER_PROBLEM = 4,
	ECHO_REPLY = 128,
	ECHO_REQUEST = 129,
	ROUTER_SOLICITATION = 133,
	ROUTER_ADVERTISEMENT = 134,
	NEIGHBOR_SOLICITATION = 135,
	NEIGHBOR_ADVERTISEMENT = 136,
	REDIRECT_MESSAGE = 137
}
