namespace SerialAPI;

internal enum SerialStatus : byte
{
	SERIAL_STATUS_ACK = 1,
	SERIAL_STATUS_BUSY,
	SERIAL_STATUS_TIMEOUT,
	SERIAL_STATUS_NO_REPLY,
	SERIAL_STATUS_INCOMMING,
	SERIAL_STATUS_DUTU_CYCLE,
	SERIAL_STATUS_CRC_ERROR,
	SERIAL_STATUS_ERROR,
	SERIAL_STATUS_MULTI_CAST
}
