namespace SerialAPI;

public enum SIPcosFrameType : byte
{
	NETWORK_MANAGEMENT_FRAME = 0,
	ROUTE_MANAGEMENT = 1,
	FIRMWARE_UPDATE = 15,
	ANSWER = 16,
	CONFIGURATION = 17,
	STATUSINFO = 18,
	TIMESLOT_CC = 19,
	DIRECT_EXECUTION = 20,
	TIME_INFORMATION = 21,
	UNCONDITIONAL_SWITCH_COMMAND = 22,
	CONDITIONAL_SWITCH_COMMAND = 23,
	LEVEL_COMMAND = 24,
	VIRTUAL_BIDCOS_COMMAND = 119
}
