namespace RWE.SmartHome.SHC.HCI.MessageIdentifier;

public enum DeviceManagementMessageIdentifier
{
	DEVMGMT_MSG_PING_REQ = 1,
	DEVMGMT_MSG_PING_RSP = 2,
	DEVMGMT_MSG_SET_CONFIG_REQ = 3,
	DEVMGMT_MSG_SET_CONFIG_RSP = 4,
	DEVMGMT_MSG_GET_CONFIG_REQ = 5,
	DEVMGMT_MSG_GET_CONFIG_RSP = 6,
	DEVMGMT_MSG_RESET_REQ = 7,
	DEVMGMT_MSG_RESET_RSP = 8,
	DEVMGMT_MSG_FACTORY_RESET_REQ = 9,
	DEVMGMT_MSG_FACTORY_RESET_RSP = 10,
	DEVMGMT_MSG_GET_OPMODE_REQ = 11,
	DEVMGMT_MSG_GET_OPMODE_RSP = 12,
	DEVMGMT_MSG_SET_OPMODE_REQ = 13,
	DEVMGMT_MSG_SET_OPMODE_RSP = 14,
	DEVMGMT_MSG_GET_DEVICEINFO_REQ = 15,
	DEVMGMT_MSG_GET_DEVICEINFO_RSP = 16,
	DEVMGMT_MSG_GET_SYSSTATUS_REQ = 17,
	DEVMGMT_MSG_GET_SYSSTATUS_RSP = 18,
	DEVMGMT_MSG_SET_AES_ENCKEY_REQ = 33,
	DEVMGMT_MSG_SET_AES_ENCKEY_RSP = 34,
	DEVMGMT_MSG_ENABLE_AES_ENCKEY_REQ = 35,
	DEVMGMT_MSG_ENABLE_AES_ENCKEY_RSP = 36,
	DEVMGMT_MSG_SET_AES_DECKEY_REQ = 37,
	DEVMGMT_MSG_SET_AES_DECKEY_RSP = 38,
	DEVMGMT_MSG_AES_DEC_ERROR_IND = 39
}
