using System;

namespace Rebex.Net;

public class SmtpRejectedRecipient
{
	private readonly string zwffx;

	private readonly SmtpResponse bmdgv;

	private readonly Exception drztx;

	public string Address => zwffx;

	public SmtpResponse Response => bmdgv;

	public Exception Error => drztx;

	internal SmtpRejectedRecipient(string address, Exception error)
	{
		zwffx = address;
		bmdgv = new SmtpResponse(550, error.Message, "550 Error generated by Rebex Mail.");
		drztx = error;
	}

	public SmtpRejectedRecipient(string address, SmtpResponse response)
	{
		zwffx = address;
		bmdgv = response;
	}
}
